name: "[.NET]Code Formatting"

inputs:
  project:
    required: true
    type: string
  project-name:
    required: true
    type: string
outputs:
  changes:
    description: "Git Diff Changes"
    value: ${{ steps.changes.outputs.changes }}

runs:
  using: "composite"
  steps:
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
    - uses: xt0rted/dotnet-format-problem-matcher@v1.2.0
    - run: dotnet tool install -g dotnet-format
      shell: bash
    - run: dotnet-format ${{ inputs.project }}
      if: always()
      shell: bash
    - id: changes
      if: always()
      run: |
        git diff >> output.patch
        GIT_DIFF=$(cat output.patch)
        GIT_DIFF="${GIT_DIFF//'%'/'%25'}"
        GIT_DIFF="${GIT_DIFF//$'\n'/'%0A'}"
        GIT_DIFF="${GIT_DIFF//$'\r'/'%0D'}"
        echo "::set-output name=changes::$GIT_DIFF"
      shell: bash
