name: "[.NET]Publish project"

on:
  workflow_dispatch:
   inputs:
      project-path:
        required: true
        type: string
      publishprofile:
        required: true
        type: string
      password:
        required: true
        type: string
      configuration:
        required: false
        type: string
        default: "Release"
  # workflow_call:
  #   inputs:
  #     project-path:
  #       required: true
  #       type: string
  #     configuration:
  #       required: false
  #       type: string
  #       default: ""



jobs:
  publish:
    runs-on: windows-latest
    
    steps:
      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v1.1
      - name: Build and deploy Application        
        run: msbuild ${{ inputs.project-path }} -property:Configuration=${{ inputs.configuration }} /restore /p:DeployOnBuild=true /p:PublishProfile=${{ inputs.publishprofile }} /p:Password=${{ inputs.password }}