name: "[.NET]Code Formatting"

on:
  workflow_call:
    inputs:
      project:
        required: true
        type: string
      project-name:
        required: true
        type: string
jobs:
  format:
    name: "Formatting ${{ inputs.project-name }}"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 6.0.x
      - uses: xt0rted/dotnet-format-problem-matcher@v1.2.0
      - run: dotnet tool install -g dotnet-format
      - run: dotnet-format ${{ inputs.project }}