name: "[.NET]Code Formatting"

on:
  workflow_call:
    inputs:
      project:
        required: true
        type: string
      project-name:
        required: true
        type: string
    outputs:
      changes:
        description: "Git Diff Changes"
        value: ${{ jobs.format.outputs.changes }}

jobs:
  format:
    name: "Formatting ${{ inputs.project-name }}"
    runs-on: ubuntu-latest
    outputs:
      changes: ${{ steps.changes.output }}
    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 6.0.x
      - uses: xt0rted/dotnet-format-problem-matcher@v1.2.0
      - run: dotnet tool install -g dotnet-format
      - run: dotnet-format ${{ inputs.project }}
      - id: changes
        run: |
          git diff >> output.patch
          GIT_DIFF=$(cat output.patch)
          GIT_DIFF="${GIT_DIFF//'%'/'%25'}"
          GIT_DIFF="${GIT_DIFF//$'\n'/'%0A'}"
          GIT_DIFF="${GIT_DIFF//$'\r'/'%0D'}"
          echo "::set-output name=output::$GIT_DIFF"
